app/urls.py
from django.urls import path
from . import views
from gallery.views import gallery, delete_img

urlpatterns = [
    path('',views.home,name='index'),
    path('create/',views.link_shortner,name='hj'),

    path('save/',views.save_data,name='save'),
    path('anonymous_save/',views.anonymous_save,name='anonymous_save'),

    path('search/',views.search,name='search'),
    path('tag/<slug:tag_slug>/',views.post_list, name='post_tag'),

    path('dashboard/',views.dashboard, name='dashboard'),
    path('dashboard_chart/',views.dashboard_chart_api, name='dashboard_chart'),
    path('test_links/', views.test_links, name='test_links'),
    path('settings/', views.settingsPage, name='settings'),
    path('tags/', views.tagsPage, name='tags'),
    path('files/', views.filesPage, name='files'),
    path('file/<str:pk>/', views.fileShare, name='fileshare'),

    path('gallery/',gallery, name="gallery"),
    path('delete_img/',delete_img, name="delete_img"),

    path('delete/',views.delete,name='delete'),
    path('delete_file/',views.deleteFile,name='delete_file'),
    path('edit/',views.edit_links,name='edit'), # Json resp+
    path('edit_link/',views.edit,name='edit_link'), # Json resp
    
    path('qr/<str:short_url>',views.qr_code,name='qr'),
    path('analytics/',views.analytics, name='analytics'),

    path('<str:pk>/',views.go,name='go'),
]

shorty/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('account/', include('accounts.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = "app.views.PagenotFound"
handler500 = "app.views.ServernotFound"

files/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Files(models.Model):
    # description = models.CharField(max_length=255, blank=True)
    document = models.FileField(upload_to='files/')
    share_url = models.CharField(max_length=50, blank=True, null=True)
    uploaded_at = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, null=True, blank=True, on_delete=models.CASCADE)
    

    def __str__(self):
        return self.document.name

    def get_size(self):
        val = self.document.size
        for x in ['bytes', 'KB', 'MB', 'GB', 'TB']:
            if val < 1024.0:
                return "%3.1f %s" % (val, x)
            val /= 1024.0

        return val

    class Meta:
        verbose_name_plural = "Files"

gallery/models.py
from statistics import mode
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Gallery(models.Model):
	image = models.ImageField(upload_to='gallery/%Y/%m/%d/')
	alt = models.CharField(max_length=50)
	user = models.ForeignKey(User, null=True, blank=True, on_delete=models.CASCADE)
	
	class Meta:
		ordering=["-id"]

	def __str__(self):
		return self.alt
		
	def get_size(self):
		val = self.image.size
		for x in ['bytes', 'KB', 'MB', 'GB', 'TB']:
			if val < 1024.0:
				return "%3.1f %s" % (val, x)
			val /= 1024.0

		return val
	
	def save(self, *args, **kwargs):
		
		super(Gallery, self).save(*args, **kwargs)

files/forms.py
from .models import Files
from django.forms import ModelForm, FileField, FileInput

class UploadFileForm(ModelForm):
    document = FileField(widget=FileInput(attrs={"class":"form-control me-2"}))
    
    class Meta:
        model = Files
        fields = ('document', 'user', 'share_url')

gallery/forms.py
from django import forms
from .models import Gallery

class GalleryForm(forms.ModelForm):
	image = forms.ImageField(widget=forms.FileInput(attrs={'class': 'form-control'}))
	alt = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Alt text for image'}))

	class Meta:
		model = Gallery
		fields = ('image', 'alt', 'user')

gallery/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.views.decorators.cache import cache_control
from gallery.models import Gallery
from .forms import GalleryForm

# Create your views here.

@login_required(login_url='login')
@cache_control(must_revalidate=True, max_age=300)
def gallery(request):
	data = Gallery.objects.filter(user=request.user.id)
	if request.method == 'POST':
		print('post')
		form = GalleryForm(request.POST, request.FILES)
		print(form)
		if form.is_valid():
			obj = form.save(commit=False)
			obj.user = request.user
			obj.save()
			
			messages.success(request, 'Image uploaded successfully.')
			return HttpResponseRedirect('/gallery')
	else:
		form = GalleryForm()
	return render(request, 'dashboard/gallery.html', {'form': form, 'data': data})

@login_required(login_url='login')
def delete_img(request):
	if request.method == 'POST':
		key = request.POST.get('id')
		try:
			obj = Gallery.objects.get(id=key)
			obj.delete()
			print('done')
		except Exception as e:
			raise
	return HttpResponseRedirect('/gallery')

app/templates/dashboard/campaign.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
  <meta name="generator" content="Hugo 0.82.0">
  <title>Dashboard Template · Bootstrap v5.0</title>

  <link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/dashboard/">



  <!-- Bootstrap core CSS -->
  <link href="{% static 'assets/dist/css/bootstrap.min.css' %}" rel="stylesheet">

  <style>
    .bd-placeholder-img {
      font-size: 1.125rem;
      text-anchor: middle;
      -webkit-user-select: none;
      -moz-user-select: none;
      user-select: none;
    }

    @media (min-width: 768px) {
      .bd-placeholder-img-lg {
        font-size: 3.5rem;
      }
    }
  </style>


  <!-- Custom styles for this template -->
  <link href="{% static 'css/dashboard.css' %}" rel="stylesheet">
</head>

<body>

  <header class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow">
    <a class="navbar-brand col-md-3 col-lg-2 me-0 px-3" href="#">Hello, {{request.user}}</a>
    <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-bs-toggle="collapse"
      data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <input class="form-control form-control-dark w-100" type="text" placeholder="Search" aria-label="Search">
    <ul class="navbar-nav px-3">
      <li class="nav-item text-nowrap">
        <a class="nav-link" href="{% url 'logout' %}">Sign out</a>
      </li>
    </ul>
  </header>

  <div class="container-fluid">
    <div class="row">
      {% include "components/navbar.html" %}


      <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
        <div
          class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
          <h1 class="h2">Campaigns</h1>
          <div class="btn-toolbar mb-2 mb-md-0">
            <div class="btn-group me-2">
              <!-- Off canvas -->
{% include 'components/newCampaignOffCanvas.html' %}
              
              <!-- End of offcanvas -->

            </div>
            <button type="button" class="btn btn-sm btn-outline-secondary dropdown-toggle">
              <span data-feather="calendar"></span>
              This week
            </button>
          </div>
        </div>

        
        <!-- end of card -->

        <!-- <canvas class="my-4 w-100" id="myChart" width="900" height="380"></canvas> -->
        <!-- start main -->

        <div class="card card-body">
            <div class="card-body">
              <h5 class="card-title">Google (site title)</h5>
              <h6 class="card-subtitle mb-2 text-muted"> www.google.com (link to shorten)</h6>
              <p class="card-text">A technology giant making new technologies accessible to people. (link description from
                crawling)</p>
  
  <!-- copy testing --> 
                <a href="https://www.google.com" class="card-link" id="k">Another link</a> <br>
              
              
              <button class="card-link btn" >Copy </button>
              <a href="#" class="card-link">Edit</a>
              <a href="#" class="card-link">Delete</a>
  
            </div>
          </div>

        <!-- end main -->
        {% include "components/deleteFileModal.html" %}
      </main>
    </div>
  </div>

  <script src="{% static 'js/customLinkcreation.js' %}"></script>
  <script src="{% static 'js/copy.js' %}"></script>

  <script src="{% static 'assets/dist/js/bootstrap.bundle.min.js' %}"></script>

  <script src="https://cdn.jsdelivr.net/npm/feather-icons@4.28.0/dist/feather.min.js"
    integrity="sha384-uO3SXW5IuS1ZpFPKugNNWqTZRRglnUJK6UAZ/gxOX80nxEkN9NcGZTftn6RzhGWE"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.4/dist/Chart.min.js"
    integrity="sha384-zNy6FEbO50N+Cg5wap8IKA4M/ZnLJgzc6w2NqACZaK0u0FXfOWRRJOnQtpZun8ha"
    crossorigin="anonymous"></script>
  <script src="{% static 'js/dashboard.js' %}"></script>
</body>

</html>

app/templates/dashboard/dashboard.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.82.0">
    <title>Dashboard | Shortly</title>

    <link rel="shortcut icon" href="{%  static 'favicon/favicon.ico' %}">
    <link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/dashboard/">

    

    <!-- Bootstrap core CSS -->
<link href="{% static 'assets/dist/css/bootstrap.min.css' %}" rel="stylesheet">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>

    
    <!-- Custom styles for this template -->
    <link href="{% static 'css/dashboard.css' %}" rel="stylesheet">
  </head>
  <body>
    
<header class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow">
  <a class="navbar-brand col-md-3 col-lg-2 me-0 px-3" href="#">Hello, {{request.user}}</a>
  <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <ul class="navbar-nav px-3">
    <li class="nav-item text-nowrap">
      <a class="nav-link" href="{% url 'logout' %}">Sign out</a>
    </li>
  </ul>
</header>

<div class="container-fluid">
  <div class="row">
    {% include 'components/navbar.html' %}

    <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
      <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Dashboard</h1>
        
      </div>

      
      <canvas class="my-4 w-100" id="myChart" width="900" height="380"></canvas>

      <div class="row">
        <div class="col-sm-3">
          <div class="card">
            <div class="card-body">
              <div class="card-title text-center">All URLs</div>
              <p class="p-3 mb-2 h4 text-center">{{l_user.count}}</p>
            </div>
          </div>
        </div>
        <div class="col-sm-3">
          <div class="card">
            <div class="card-body">
              <div class="card-title text-center">Total Clicks</div>
              <p class="p-3 mb-2 h4 text-center">{{l_all}}</p>
            </div>
          </div>
        </div>
        <div class="col">
          <div class="card">
            
            <div class="card-body">
              <div class="card-title">Top 3 URLs</div>
              <!-- <div class="d-flex justify-content-between"> -->
                {% for link in top_3 %}
              
                <div class="row">
                  <div class="col-11">
              <a href="{% url 'test_links' %}#card{{link.id}}" class="p-2 mb-2 text-dark text-decoration-none">{{link.url}}</a>
              </div>
              <div class="col text-end">{{link.total_clicks}}
            <!-- </div> --> 
          </div>
        </div>
        {% endfor %}
        
</div>
          </div>
        </div>
      </div>

    </main>
  </div>
</div>


    <script src="{% static 'assets/dist/js/bootstrap.bundle.min.js' %}"></script>

      <script src="https://cdn.jsdelivr.net/npm/feather-icons@4.28.0/dist/feather.min.js" integrity="sha384-uO3SXW5IuS1ZpFPKugNNWqTZRRglnUJK6UAZ/gxOX80nxEkN9NcGZTftn6RzhGWE" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.2.0/Chart.min.js"></script>
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
      {% include 'ajax/dashboardChartScript.html' %}
  </body>
</html>

app/templates/dashboard/files.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
  <meta name="generator" content="Hugo 0.82.0">
  <title>Files | Shortly</title>

  <link rel="shortcut icon" href="{%  static 'favicon/favicon.ico' %}">
  <link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/dashboard/">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>



  <!-- Bootstrap core CSS -->
  <link href="{% static 'assets/dist/css/bootstrap.min.css' %}" rel="stylesheet">

  <style>
    .bd-placeholder-img {
      font-size: 1.125rem;
      text-anchor: middle;
      -webkit-user-select: none;
      -moz-user-select: none;
      user-select: none;
    }

    @media (min-width: 768px) {
      .bd-placeholder-img-lg {
        font-size: 3.5rem;
      }
    }
  </style>


  <!-- Custom styles for this template -->
  <link href="{% static 'css/dashboard.css' %}" rel="stylesheet">
</head>

<body>

  <header class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow">
    <a class="navbar-brand col-md-3 col-lg-2 me-0 px-3" href="#">Hello, {{request.user}}</a>
    <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-bs-toggle="collapse"
      data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <input class="form-control form-control-dark w-100" type="text" placeholder="Search" aria-label="Search">
    <ul class="navbar-nav px-3">
      <li class="nav-item text-nowrap">
        <a class="nav-link" href="{% url 'logout' %}">Sign out</a>
      </li>
    </ul>
  </header>

  <div class="container-fluid">
    <div class="row">
      {% include "components/navbar.html" %}


      <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
        <div
          class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
          <h1 class="h2">Files</h1>
          
        </div>

        
        <!-- end of card -->

        <!-- <canvas class="my-4 w-100" id="myChart" width="900" height="380"></canvas> -->
        <!-- Messages and warnings -->
        
        {% if messages %}
        
        {% for message in messages %}
        <div {% if "error" in message.tags %} class="alert alert-danger" {% else %} class="alert alert-{{ message.tags }}" {% endif %} id="message">
          <ul>
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
          </ul>
        </div>
        {% endfor %}
        
        {% endif %}
      

      <!-- message section end -->
        <!-- start main -->
        
        <form method="post" class="d-flex" enctype="multipart/form-data">
          {% csrf_token %}

          {{form.document}}
        <!-- <input type="file" name="files" id="" class="form-control me-2" placeholder="Create new files "> -->
        <input type="Submit" value="Submit" class="btn btn-primary">
        </form>

        {% for file in data %}

        <div class="card" id="card{{file.id}}">
          <div class="card-body">
            <div class="row">
              <p class="card-title col-6 mt-2">
                <a href="{{file.document.url}}" class="text-dark text-decoration-none" target="_blank">{{file.document.name}}</a>
              </p>
              <div class="date col-2 mt-2 text-end">{{file.get_size}}</div>
              <div class="date col-2 mt-2 text-end">{{file.uploaded_at.date}}</div>
              <div class="dropdown col-2 text-end">
                <a class="btn btn-sm me-md-2 " href="#" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown"
                  aria-expanded="false">
                  <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                    class="bi bi-three-dots-vertical" viewBox="0 0 16 16">
                    <path
                      d="M9.5 13a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0zm0-5a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0zm0-5a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0z" />
                  </svg>
                </a>
                <!-- <button class="btn btn-primary btn-sm">Edit</button> -->
                <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                  <li><a class="btn btn-primary dropdown-item" id="editContactModal" data-catid="{{data.pk}}" data-bs-toggle="modal" data-bs-target="#editModal">
                    QR code
                  </a></li>
                  <li><a href="{{file.document.url}}" class="btn btn-primary dropdown-item btn-delete" download="{{file.document.url}}">
                    Download
                  </a></li>
                  
                  <li><a class="btn btn-primary dropdown-item" data-bs-toggle="modal" data-bs-target="#fileModal{{file.id}}">
                    Delete
                  </a></li>
                  
                  <!-- <li><a class="dropdown-item" href="#">Something else here</a></li> -->
                  <li><a class="btn btn-primary dropdown-item" id="editContactModal" data-catid="{{file.pk}}" data-bs-toggle="modal" data-bs-target="#shareModal{{file.id}}">
                    Share
                  </a></li>
                  <!-- <li><a class="dropdown-item" href="#">Something else here</a></li> -->
                </ul>
              </div>
            </div>
          </div>
        </div>
        {% include "components/deleteFileModal.html" %}
        {% include "components/shareFileModal.html" %}
        {% endfor %}


        <!-- end main -->
        
      </main>
    </div>
  </div>

  <!-- <script src="{% static 'js/customLinkcreation.js' %}"></script> -->
  <script src="{% static 'js/copy.js' %}"></script>

  <script src="{% static 'assets/dist/js/bootstrap.bundle.min.js' %}"></script>

  <script src="https://cdn.jsdelivr.net/npm/feather-icons@4.28.0/dist/feather.min.js"
    integrity="sha384-uO3SXW5IuS1ZpFPKugNNWqTZRRglnUJK6UAZ/gxOX80nxEkN9NcGZTftn6RzhGWE"
    crossorigin="anonymous"></script>
  <!-- <script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.4/dist/Chart.min.js"
    integrity="sha384-zNy6FEbO50N+Cg5wap8IKA4M/ZnLJgzc6w2NqACZaK0u0FXfOWRRJOnQtpZun8ha"
    crossorigin="anonymous"></script>
  <script src="{% static 'js/dashboard.js' %}"></script> -->
  <script>
    feather.replace();
    
    // Deleting Data
    $(".btn-file-delete").click(function () {
    
    let id = $(this).attr("data-sid")
    let csr = $("input[name=csrfmiddlewaretoken]").val();

    mydata = { sid:id, csrfmiddlewaretoken:csr }
    $.ajax({
        url: "{% url 'delete_file' %}",
        method: 'POST',
        data: mydata,
        success: function (data) {
          if (data.status == 1) {
            $(`#fileModal${data.id}`).modal('hide');
            $(`#card${data.id}`).fadeOut()
            
            }
          else if(data.status == 0){
            console.log('link already deleted or an error occured')
          }
        }
        })
    });
  </script>
  <!-- <script src="{% static 'js/copy.js' %}"></script> -->
  
</body>

</html>

app/templates/dashboard/gallery.html
{% extends 'dashboard/page_base.html' %}

{% block title %}
Gallery | Shortly
{% endblock title %}

{% block main %}

    <div
      class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
      <h1 class="h2">Gallery</h1>
      
    </div>

    
    <!-- end of card -->

    <!-- <canvas class="my-4 w-100" id="myChart" width="900" height="380"></canvas> -->
    <!-- Messages and warnings -->
    
    {% if messages %}
    
    {% for message in messages %}
    <div {% if "error" in message.tags %} class="alert alert-danger" {% else %} class="alert alert-{{ message.tags }}" {% endif %} id="message">
      <ul>
        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
      </ul>
    </div>
    {% endfor %}
    
    {% endif %}
  

  <!-- message section end -->
    <!-- start main -->
    <form method="post" enctype="multipart/form-data" class="form-control">
      {% csrf_token %}
      <div class="mb-3">
        <label for="id_image" class="form-label">Upload image</label>
        <!-- <input type="file" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp"> -->
        {{form.image}}
        <!-- <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div> -->
      </div>
      <div class="mb-3">
        <label for="id_alt" class="form-label">Alt text for Image</label>
        <!-- <input type="password" class="form-control" id="exampleInputPassword1"> -->
        {{form.alt}}
      </div>
      
      <button type="submit" class="btn btn-primary">Submit</button>
    </form>
    <!-- <form method="post" class="d-flex" enctype="multipart/form-data">
      {% csrf_token %}

      {{form.image}}
      {{form.alt}}
    <input type="Submit" value="Submit" class="btn btn-primary">
    </form> -->
<hr>
    {% for file in data %}

    <div class="card" id="card{{file.id}}">
      <div class="card-body">
        <div class="row">
          <p class="card-title col-6 mt-2">
            <a href="{{file.image.url}}" class="text-dark text-decoration-none" target="_blank">{{file.image.name}}</a>
          </p>
          <div class="date col-2 mt-2 text-end">{{file.uploaded_at.date}}</div>
          <div class="date col-2 mt-2 text-end">{{file.get_size}}</div>
          <div class="dropdown col-2 text-end">
            <a class="btn btn-sm me-md-2 " href="#" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown"
              aria-expanded="false">
              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                class="bi bi-three-dots-vertical" viewBox="0 0 16 16">
                <path
                  d="M9.5 13a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0zm0-5a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0zm0-5a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0z" />
              </svg>
            </a>
            <!-- <button class="btn btn-primary btn-sm">Edit</button> -->
            <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
              <!-- <li><a class="btn btn-primary dropdown-item" id="editContactModal" data-catid="{{data.pk}}" data-bs-toggle="modal" data-bs-target="#editModal">
                QR code
              </a></li> -->
              <li><a href="{{file.image.url}}" class="btn btn-primary dropdown-item btn-delete" download="{{file.image.url}}">
                Download
              </a></li>
              
              <li><a class="btn btn-primary dropdown-item" data-bs-toggle="modal" data-bs-target="#fileModal{{file.id}}">
                Delete
              </a></li>
              
              <!-- <li><a class="dropdown-item" href="#">Something else here</a></li> -->
              <!-- <li><a class="btn btn-primary dropdown-item" id="editContactModal" data-catid="{{file.pk}}" data-bs-toggle="modal" data-bs-target="#shareModal{{file.id}}">
                Share
              </a></li> -->
              <!-- <li><a class="dropdown-item" href="#">Something else here</a></li> -->
            </ul>
          </div>
        </div>
      </div>
    </div>
    {% include "components/deleteImageModal.html" %}
    
    {% endfor %}

    <!-- end main -->

{% endblock main %}

app/templates/dashboard/settings.html
{% extends 'dashboard/page_base.html' %}

{% block title %}
User Settings
{% endblock title %}

{% block main %}
  <div
      class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
      <h1 class="h2">User Settings</h1>    
    </div>

    <div class="card card-body">
        <div class="card-body">
          <h5 class="card-title">User name : {{user}}</h5>
          <h6 class="card-subtitle mb-2 text-muted">E-mail id : {{user.email}}</h6>
          
         
          <a href="{% url 'change_password' %}" class="card-link btn btn-outline-dark" >Change Password </a>
          <a href="#" class="card-link btn btn-outline-dark">Edit</a>
          <a href="#" class="card-link btn btn-outline-dark">Delete Account</a>

        </div>
    </div>
{% endblock main %}

{% block script %}

{% endblock script %}